conn sys/oracle as sysdba;

-- Setup Moodle user.

ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;
CREATE USER moodle IDENTIFIED BY "m@0dl3";

GRANT CONNECT,RESOURCE,DBA TO moodle;
GRANT CREATE SESSION TO moodle WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO moodle;
GRANT EXECUTE ON DBMS_LOCK to moodle;
GRANT EXECUTE ON moodlelib to moodle;
