services:
  webserver:
    environment:
      MOODLE_DOCKER_DBTYPE: sqlsrv
      MOODLE_DOCKER_DBUSER: sa
  db:
    image: moodlehq/moodle-db-mssql:${MOODLE_DOCKER_DB_VERSION:-latest}
    environment:
        ACCEPT_EULA: "y"
        SA_PASSWORD: "m@0dl3ing"
