services:
  db:
    image: mysql:${MOODLE_DOCKER_DB_VERSION:-5.6}
    command: >
                --character-set-server=utf8mb4
                --collation-server=utf8mb4_bin
                --innodb_file_format=barracuda
                --innodb_file_per_table=On
                --innodb_large_prefix=On
