services:
  webserver:
    environment:
      MOODLE_DOCKER_DBTYPE: sqlsrv
      MOODLE_DOCKER_DBUSER: sa
  db:
    image: moodlehq/moodle-db-mssql:${MOODLE_DOCKER_DB_VERSION:-latest}
    environment:
        ACCEPT_EULA: "y"
        MSSQL_SA_PASSWORD: "m@0dl3ing"
        MSSQL_WAIT4READY: ${MOODLE_DOCKER_DB_WAIT4READY:-60}
