version: "2.3"
services:
  webserver:
    environment:
      MOODLE_DOCKER_APP: "true"
  moodleapp:
    image: node:11
    working_dir: /app
    command: npm run ionic:serve
    volumes:
      - "${MOODLE_DOCKER_APP_PATH}:/app"
    healthcheck:
      test: "curl -f http://localhost:8100 || exit 1"
      interval: 10s
      timeout: 3s
      start_period: 30s
    expose:
      - 8100
      - 35729
      - 53703
    ports:
      - "8100:8100"
      - "35729:35729"
      - "53703:53703"
