version: "2.3"
services:
  webserver:
    volumes:
      - "${ASSETDIR}/web/apache2_mailhog.conf:/etc/apache2/conf-enabled/apache2_mailhog.conf"
    depends_on:
      - mailhog
  mailhog:
    image: mailhog/mailhog
