#!/usr/bin/env bash
command=''
quoteopen='no'
for (( i=2; i<=$#; i++)); do
  part=${!i}
  if [[ "$quoteopen" == 'yes' && "$part" == "-"* ]]; then
    command="$command\""
    quoteopen='no'
  fi
  eqsign="${part//[^=]}"
  if [ ${#eqsign} -eq 1 ]; then
    part="${part//=/=\"}"
    quoteopen='yes'
  fi
  command="$command $part"
done

if [ "$quoteopen" == 'yes' ]; then
  command="$command\""
  quoteopen='no'
fi